export const routes = {
  home: "",
  about: "/about",
  partnershipModel: "/partnership-model",
  howWeWork: "/how-we-work",
  solutions: {
    compressors: "/solutions/compressors",
    compressorParts: "/solutions/compressor-parts",
    pumps: "/solutions/pumps",
    hydraulics: "/solutions/hydraulics",
    valves: "/solutions/valves",
    automation: "/solutions/automation",
    mechanical: "/solutions/mechanical",
    consumables: "/solutions/consumables",
    filtration: "/solutions/filtration",
    pneumatics: "/solutions/pneumatics",
  },
  brands: "/brands",
  brand: (slug: string) => `/brands/${slug}`,
  parts: "/parts",
  part: (slug: string) => `/parts/${slug}`,
  industries: "/industries",
  industry: (slug: string) => `/industries/${slug}`,
  applications: "/applications",
  application: (slug: string) => `/applications/${slug}`,
  manufacturingNetwork: "/manufacturing-network",
  manufacturingCapability: "/manufacturing-capability",
  compatibleSolutions: "/compatible-solutions",
  partners: {
    serviceCenters: "/partners/service-centers",
    distributors: "/partners/distributors",
    regionalPartners: "/partners/regional-partners",
  },
  qualityControl: "/quality-control",
  supplyChainNetwork: "/supply-chain-network",
  cases: "/cases",
  case: (slug: string) => `/cases/${slug}`,
  faq: "/faq",
  contact: "/contact",
  submitRequirement: "/submit-requirement",
  request: "/request",
} as const;
